version: "3.9"

services:
  mysql_container:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: koyejo
      MYSQL_DATABASE: library_db
      MYSQL_USER: motunrayo
      MYSQL_PASSWORD: koyejo
    ports:
      - "3300:3306" 
    volumes:
      - mysql_data:/var/lib/mysql 
    networks:
      - library_api_network 

  frontend-api:
    build: ./frontend-api
    ports:
      - "8000:8000"
    depends_on:
      - mysql_container
    environment:
      - SQLALCHEMY_DATABASE_URL=mysql+mysqlconnector://motunrayo:koyejo@mysql_container:3306/library_db
      - BACKEND_API_URL=http://backend-api:8001
    networks:
      - library_api_network

  backend-api:
    build: ./backend-api
    ports:
      - "8001:8001"
    depends_on:
      - mysql_container
    environment:
      - SQLALCHEMY_DATABASE_URL=mysql+mysqlconnector://motunrayo:koyejo@mysql_container:3306/library_frontend
      - FRONTEND_API_URL=http://frontend-api:8000
    networks:
      - library_api_network

volumes:
  mysql_data:

networks:
  library_api_network:
    driver: bridge